name: 🚀 Auto Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Cho phép chạy manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚀 Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd /var/www/docbanking
          chmod +x deploy.sh
          ./deploy.sh
